#!/bin/bash -xe

#apt-get install ruby-devel
#gem install rake
#gem install krane
#gem install ejson

egrep "^ubuntu" "favPkgs.txt" | cut -d: -f2 | while read pkg; do
  apt-get -y install $pkg
done

#./setupZsh
#./install-oh-my-zsh
#./installChromeBrowser

#apt-get install virtualbox
