#!/bin/bash -xe

downloadDir=$(mktemp -d)

wget "https://dl.google.com/go/$(curl -sL 'https://golang.org/VERSION?m=text').linux-amd64.tar.gz" -P ${downloadDir?}

rm -rf /usr/local/go && tar -C /usr/local -xzf ${downloadDir}/go1.17.8.linux-amd64.tar.gz

#rm -rf ${downloadDir?}
