#!/bin/bash -xe
if [ ! -d ~/.conky ]; then
  mkdir -p ~/.conky
  cd ~/.conky
  git clone https://github.com/ChrisTitusTech/titus-conky
  cp titus-conky/conky-startup.sh .
  cp titus-conky/Titus.conkyrc .
fi

ln -s ${HOME}/.conky/conky-startup.sh /etc/profile.d
