#!/bin/bash

TMPDIR=$(mktemp -d)
wget -P ${TMPDIR?} https://github.com/derailed/k9s/releases/download/v0.25.18/k9s_Linux_x86_64.tar.gz
mkdir -p /opt/k9scli.io
zcat ${TMPDIR}/k9s_Linux_x86_64.tar.gz | (cd /opt/k9scli.io; tar xf -)
chown -R root:root /opt/k9scli.io
ln -fs /opt/k9scli.io/k9s /usr/local/bin/k9s
rm -rf ${TMPDIR}
