#!/bin/bash -xe
if [ ! -d ~/.conky ]; then
  mkdir -p ~/.conky
  cd ~/.conky
  git clone https://github.com/ChrisTitusTech/titus-conky
#  cp titus-conky/conky-startup.sh .
  cp titus-conky/Titus.conkyrc .
  cat << 'EOF' > ~/.conky/conky-startup.sh
if [ "$(whoami)" = "rtai" ]; then
  killall -q conky
  sleep 20s && conky -c "/home/rtai/.conky/Titus.conkyrc" &
fi
EOF
fi

sudo ln -fs ${HOME}/.conky/conky-startup.sh /etc/profile.d
